name: Multi-stage Docker Build

author: Eric Stern

description: Build Docker images to maximize layer caching and minimize build times

inputs:
  build-args:
    description: A comma-separated list of `--build-arg` flags
    required: false
    default: ''
  context:
    description: Build context. Default to `.`
    required: false
    default: '.'
  dockerfile:
    description: Path to Dockerfile
    required: false
    default: ''
  parallel:
    description: Build in parallel
    required: false
    default: false
  repository:
    required: true
    description: Repository that all of the images and tags will pull from and push to
  stages:
    required: true
    description: A comma-separated list of build stages
  server-stage:
    required: true
    description: Docker target for server
  tag-latest-on-default:
    default: true
    description: Automatically create a "latest" tag when the action is run on the default branch (defaults to `true`)
    required: false
  custom-tag:
    default: ''
    required: false
    description: A user-defined tag to apply to successfully built and pushed images
  testenv-stage:
    required: false
    description: Docker target for testing
  quiet:
    required: false
    default: true
    description: Send `--quiet` flag to docker commands

outputs:
  commit:
    description: The full commit hash used for tags
  server-tag:
    description: Commit-specific tag for server
  testenv-tag:
    description: Commit-specific tag for test env

branding:
  color: blue
  icon: package

runs:
  using: node16
  main: dist/index.js
